import '/styles/style.css'
import '/styles/components/mobileMenu.css'
import '/styles/components/header.css'
import '/styles/components/hero.css'
import '/styles/components/about.css'
import '/styles/components/whatWeOffer.css'
import '/styles/components/teams.css'
import '/styles/components/testimonials.css'
import '/styles/components/subscribe.css'
import '/styles/components/contact.css'
import '/styles/components/footer.css'
import '/styles/utility.css'

import '/src/mobileMenu'
import '/src/darkMode'
import '/src/carousel.js'